name: Test and Deploy docker webapp image

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-docker@v2
      with:
        dockerfile: Dockerfile

    - name: Build Docker image
      run: docker build -t webapp .

    - name: Run test
      run: |
        # run the container and test its behavior
        docker run --rm --name webapp curl http://localhost:8080

    - name: Log in to Docker Hub
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

  deploy:
    needs: build_and_test
    runs-on: ubuntu-latest

    steps:
      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag and Push Docker image
        run: |
          # Tag with the created tag name and push to Docker Hub
          docker tag my-docker-image ${{ secrets.DOCKERHUB_USERNAME }}/my-docker-image:${{ github.ref }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-docker-image:${{ github.ref }}
