name: Test docker webapp

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-docker@v2
      with:
        dockerfile: Dockerfile

    - name: Build Docker image
      run: docker build -t webapp .

    - name: Run test
      run: |
        # run a container and test its behavior
        docker run --rm --name webapp -d -p 80:80 webapp

